version: '3'

services:
    rvr_server:
        build:
            context: ./
            dockerfile: Dockerfile
        privileged: true
        command: ros2 launch rvr_bringup portal_and_server.launch.py
        environment:
          - MOCK_RVR=${MOCK_RVR:-false}
          - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
        volumes:
          - /dev:/dev
        network_mode: "host"
        ipc: "host"
        pid: "host"
