version: '3'

services:
    rvr_server:
        build:
            context: ./
            dockerfile: Dockerfile
        image: esimkowitz/sphero-rvr-ros2:latest
        privileged: true
        ports:
          - '8080:8080'
        command: . /apps/scripts/container/docker_compose_start_robot.sh
        volumes:
          - /dev:/dev