version: '3'

services:
    rvr_server:
        build:
            context: ./
            dockerfile: Dockerfile
        image: esimkowitz/sphero-rvr-ros2:latest
        privileged: true
        ports:
          - '8080:8080'
        command: ros2 launch rvr_bringup portal_and_server.launch.py
        volumes:
          - /dev/ttyS0:/dev/ttyS0