version: '3'

services:
    rvr_server:
        build:
            context: ./
            dockerfile: Dockerfile
        image: esimkowitz/sphero-rvr-ros2:latest
        privileged: true
        ports:
          - '8080:8080'
        command: python3 sphero-sdk/sphero-sdk-raspberry-python/getting_started/observer/leds/set_all_leds.py && ros2 launch rvr_bringup portal_and_server.launch.py
        volumes:
          - /dev:/dev